#![recursion_limit = "256"]


[package]
name = "digitrec_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
json = "0.12.4"
ndarray = "0.16.1"
rand = "0.8.5"
serde_json = "1.0.125"
